#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Manual de Usuario - Sistema PAF Hospital de Niños J.M. de los Ríos
Generated via ReportLab + HTML/Playwright cover
"""

import os
import sys
import hashlib
import subprocess

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    Image, KeepTogether, CondPageBreak, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
ACCENT       = colors.HexColor('#5d39cc')
TEXT_PRIMARY  = colors.HexColor('#1b1a18')
TEXT_MUTED    = colors.HexColor('#7d7a71')
BG_SURFACE   = colors.HexColor('#e5e3df')
BG_PAGE      = colors.HexColor('#f6f5f3')

# Semantic colors for PAF status
GREEN_STATUS  = colors.HexColor('#16a34a')
YELLOW_STATUS = colors.HexColor('#d97706')
RED_STATUS    = colors.HexColor('#dc2626')

# Table colors
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Page setup ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
CONTENT_W = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# Orphan heading threshold
H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans-Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/freefont/FreeMono.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold')
registerFontFamily('LiberationSans', normal='LiberationSans', bold='LiberationSans-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# ━━ Styles ━━
BODY_FONT = 'LiberationSerif'
HEADING_FONT = 'LiberationSans'

# Title page styles
styles = getSampleStyleSheet()

style_title_cover = ParagraphStyle(
    'TitleCover', fontName=HEADING_FONT, fontSize=32, leading=40,
    alignment=TA_CENTER, textColor=ACCENT, spaceAfter=12
)

style_subtitle_cover = ParagraphStyle(
    'SubtitleCover', fontName=BODY_FONT, fontSize=16, leading=22,
    alignment=TA_CENTER, textColor=TEXT_MUTED, spaceAfter=8
)

# Body styles
style_h1 = ParagraphStyle(
    'H1Custom', fontName=HEADING_FONT, fontSize=22, leading=28,
    textColor=ACCENT, spaceBefore=18, spaceAfter=10,
    alignment=TA_LEFT
)

style_h2 = ParagraphStyle(
    'H2Custom', fontName=HEADING_FONT, fontSize=16, leading=22,
    textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8,
    alignment=TA_LEFT
)

style_h3 = ParagraphStyle(
    'H3Custom', fontName=HEADING_FONT, fontSize=13, leading=18,
    textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6,
    alignment=TA_LEFT
)

style_body = ParagraphStyle(
    'BodyCustom', fontName=BODY_FONT, fontSize=10.5, leading=17,
    textColor=TEXT_PRIMARY, spaceBefore=2, spaceAfter=6,
    alignment=TA_JUSTIFY, firstLineIndent=0
)

style_body_indent = ParagraphStyle(
    'BodyIndent', parent=style_body, leftIndent=20
)

style_bullet = ParagraphStyle(
    'BulletCustom', parent=style_body, leftIndent=24, bulletIndent=12,
    spaceBefore=2, spaceAfter=3
)

style_tip = ParagraphStyle(
    'TipCustom', fontName=BODY_FONT, fontSize=10, leading=16,
    textColor=colors.HexColor('#1e40af'), spaceBefore=6, spaceAfter=6,
    leftIndent=16, rightIndent=16, backColor=colors.HexColor('#eff6ff'),
    borderPadding=8, borderColor=colors.HexColor('#3b82f6'),
    borderWidth=1, borderRadius=4
)

style_warning = ParagraphStyle(
    'WarningCustom', fontName=BODY_FONT, fontSize=10, leading=16,
    textColor=colors.HexColor('#92400e'), spaceBefore=6, spaceAfter=6,
    leftIndent=16, rightIndent=16, backColor=colors.HexColor('#fef3c7'),
    borderPadding=8, borderColor=colors.HexColor('#f59e0b'),
    borderWidth=1, borderRadius=4
)

style_role_header = ParagraphStyle(
    'RoleHeader', fontName=HEADING_FONT, fontSize=14, leading=20,
    textColor=colors.white, spaceBefore=0, spaceAfter=0,
    alignment=TA_CENTER
)

style_caption = ParagraphStyle(
    'CaptionCustom', fontName=BODY_FONT, fontSize=9, leading=14,
    textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6,
    alignment=TA_CENTER
)

# Table styles
style_th = ParagraphStyle(
    'TableHeader', fontName=HEADING_FONT, fontSize=10, leading=14,
    textColor=colors.white, alignment=TA_CENTER
)

style_td = ParagraphStyle(
    'TableCell', fontName=BODY_FONT, fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER
)

style_td_left = ParagraphStyle(
    'TableCellLeft', fontName=BODY_FONT, fontSize=9.5, leading=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT
)

# TOC styles
style_toc_h1 = ParagraphStyle(
    'TOCHeading1', fontName=HEADING_FONT, fontSize=13, leading=22,
    leftIndent=20, textColor=TEXT_PRIMARY
)

style_toc_h2 = ParagraphStyle(
    'TOCHeading2', fontName=BODY_FONT, fontSize=11, leading=18,
    leftIndent=40, textColor=TEXT_MUTED
)


# ━━ TocDocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


# ━━ Helper functions ━━
def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def add_major_section(text):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style_h1, level=0),
    ]

def make_table(data, col_widths=None, has_header=True):
    """Create a styled table with standard formatting."""
    if col_widths is None:
        col_widths = [CONTENT_W / len(data[0])] * len(data[0])
    
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ]
    if has_header:
        style_cmds.extend([
            ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
            ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ])
        for i in range(1, len(data)):
            bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    
    t.setStyle(TableStyle(style_cmds))
    return t

def role_banner(role_name, color_hex):
    """Create a colored role banner."""
    bg_color = colors.HexColor(color_hex)
    data = [[Paragraph('<b>%s</b>' % role_name, style_role_header)]]
    t = Table(data, colWidths=[CONTENT_W], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg_color),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return t

def tip_box(text):
    return Paragraph(text, style_tip)

def warning_box(text):
    return Paragraph(text, style_warning)

def bullet_list(items):
    """Create a list of bullet paragraphs."""
    result = []
    for item in items:
        result.append(Paragraph(
            '<bullet>&bull;</bullet> %s' % item, style_bullet
        ))
    return result

def numbered_list(items):
    """Create a numbered list."""
    result = []
    for i, item in enumerate(items, 1):
        result.append(Paragraph(
            '<b>%d.</b> %s' % (i, item), style_body_indent
        ))
    return result

def step_list(items):
    """Create a step-by-step guide with visual emphasis."""
    result = []
    for i, item in enumerate(items, 1):
        result.append(Paragraph(
            '<b>Paso %d:</b> %s' % (i, item), style_body_indent
        ))
    return result


# ━━ CONTENT ━━
def build_content():
    story = []

    # ──────────────────────────────────────────────
    # TABLE OF CONTENTS
    # ──────────────────────────────────────────────
    story.append(Paragraph('<b>Contenido</b>', ParagraphStyle(
        'TOCTitle', fontName=HEADING_FONT, fontSize=22, leading=28,
        textColor=ACCENT, spaceBefore=12, spaceAfter=16, alignment=TA_LEFT
    )))
    
    toc = TableOfContents()
    toc.levelStyles = [style_toc_h1, style_toc_h2]
    story.append(toc)
    story.append(PageBreak())

    # ──────────────────────────────────────────────
    # 1. INTRODUCCION
    # ──────────────────────────────────────────────
    story.extend(add_major_section('1. Introduccion al Sistema PAF'))
    
    story.append(Paragraph(
        'El Sistema de Seguimiento de Porcentaje de Avance Fisico (PAF) es una plataforma web '
        'disenada para el Hospital de Ninos J.M. de los Rios, que permite monitorear en tiempo real '
        'el progreso de las obras de recuperacion institucional. El sistema implementa un flujo de '
        'aprobacion secuencial de 3 niveles y un mecanismo de objecion/subsanacion. Este manual '
        'le guiara en el uso del sistema segun su perfil de usuario.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Que es el PAF?', style_h2, level=1))
    story.append(Paragraph(
        'El PAF (Porcentaje de Avance Fisico) es un indicador que mide el progreso real de las obras '
        'respecto al planificado. Se calcula como un promedio ponderado donde cada frente de trabajo '
        'tiene un peso relativo asignado. El valor se expresa en porcentaje (0% a 100%) y se '
        'codifica por colores:',
        style_body
    ))
    
    # PAF color table
    paf_data = [
        [Paragraph('<b>Rango</b>', style_th), Paragraph('<b>Color</b>', style_th), Paragraph('<b>Significado</b>', style_th)],
        [Paragraph('0%', style_td), Paragraph('Gris', style_td), Paragraph('Sin avance registrado', style_td_left)],
        [Paragraph('Menos de 30%', style_td), Paragraph('Rojo', style_td), Paragraph('Avance critico - requiere atencion', style_td_left)],
        [Paragraph('30% - 70%', style_td), Paragraph('Amarillo', style_td), Paragraph('Avance intermedio - en progreso', style_td_left)],
        [Paragraph('Mas de 70%', style_td), Paragraph('Verde', style_td), Paragraph('Avance satisfactorio', style_td_left)],
    ]
    story.append(Spacer(1, 12))
    story.append(make_table(paf_data, [CONTENT_W*0.2, CONTENT_W*0.2, CONTENT_W*0.6]))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Perfiles de Usuario', style_h2, level=1))
    story.append(Paragraph(
        'El sistema cuenta con siete perfiles operativos, cada uno con funciones especificas '
        'que se ajustan a su rol dentro del proyecto. Los avances pasan por un sistema de '
        'aprobacion secuencial de 3 niveles: Nivel 1 (Ingeniera Residente), Nivel 2 (Inspector MPPOP) '
        'y Nivel 3 (Directivo Hospital). El Webmaster puede aprobar cualquier nivel sin seguir '
        'la secuencia.',
        style_body
    ))
    story.append(Spacer(1, 6))
    
    roles_data = [
        [Paragraph('<b>Perfil</b>', style_th), Paragraph('<b>Funcion Principal</b>', style_th)],
        [Paragraph('Webmaster', style_td), Paragraph('Administracion total del sistema, usuarios y aprobacion de cualquier nivel', style_td_left)],
        [Paragraph('Contratista', style_td), Paragraph('Reportar avances de obra, subir evidencia fotografica y declarar subsanaciones', style_td_left)],
        [Paragraph('Inspector', style_td), Paragraph('Crear alcances, aprobar en Nivel 2 (MPPOP), objetar y crear avances', style_td_left)],
        [Paragraph('Ingeniera Residente', style_td), Paragraph('Declarar obra concluida en Nivel 1, crear avances y objetar', style_td_left)],
        [Paragraph('Directivo Hospital', style_td), Paragraph('Dar conformidad final en Nivel 3 y objetar', style_td_left)],
        [Paragraph('Ingenieria Hospital', style_td), Paragraph('Consulta de avance y alcance (solo lectura)', style_td_left)],
        [Paragraph('Visitante', style_td), Paragraph('Solo lectura en Dashboard, Alcance y Avance (sin acciones)', style_td_left)],
    ]
    story.append(make_table(roles_data, [CONTENT_W*0.35, CONTENT_W*0.65]))
    story.append(Spacer(1, 12))

    story.append(tip_box(
        '<b>Consejo:</b> Cada perfil tiene acceso solo a las funciones necesarias para su rol. '
        'Si necesita realizar una accion que no le esta disponible, contacte al Inspector o '
        'Webmaster del sistema.'
    ))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 2. ACCESO AL SISTEMA
    # ──────────────────────────────────────────────
    story.extend(add_major_section('2. Acceso al Sistema'))
    
    story.append(add_heading('Pagina de Inicio', style_h2, level=1))
    story.append(Paragraph(
        'Al ingresar a la direccion del sistema en su navegador web, vera la pagina de inicio '
        '(Landing Page) del proyecto. Esta pagina muestra informacion general del proyecto, '
        'instituciones participantes, estadisticas publicas y una galeria fotografica del avance '
        'de obras. No necesita iniciar sesion para ver esta informacion.',
        style_body
    ))
    story.append(Spacer(1, 6))

    story.append(add_heading('Como Iniciar Sesion', style_h2, level=1))
    story.append(Paragraph(
        'Para acceder a las funciones del sistema segun su perfil, debe iniciar sesion:',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en el boton <b>"Iniciar Sesion"</b> ubicado en la barra superior de la pagina, '
        'o en el boton <b>"Ver Avance de Obras en Tiempo Real"</b> de la seccion principal.',
        'Se abrira una ventana modal donde debe ingresar su <b>correo electronico</b> y '
        '<b>contrasena</b> proporcionados por el Webmaster.',
        'Haga clic en <b>"Iniciar Sesion"</b>. Si los datos son correctos, ingresara al panel principal.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Importante:</b> No intente registrarse por su cuenta. Los usuarios son creados '
        'exclusivamente por el Webmaster del sistema. Si no tiene credenciales, solicite '
        'su acceso al equipo de gestion.'
    ))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Cambio de Contrasena Obligatorio', style_h2, level=1))
    story.append(Paragraph(
        'La primera vez que ingrese al sistema, se le solicitara cambiar su contrasena por '
        'razones de seguridad. Este proceso es obligatorio y no podra usar el sistema hasta '
        'completarlo.',
        style_body
    ))
    story.extend(step_list([
        'Al iniciar sesion por primera vez, aparecera el formulario de cambio de contrasena.',
        'Ingrese su <b>contrasena actual</b> (la proporcionada por el Webmaster).',
        'Cree una <b>nueva contrasena</b> (minimo 8 caracteres, incluyendo mayuscula, minuscula, numero y caracter especial). No puede ser igual a la actual.',
        '<b>Confirme la nueva contrasena</b> escribiendola nuevamente.',
        'Haga clic en <b>"Cambiar Contrasena"</b>.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(tip_box(
        '<b>Consejo:</b> La contrasena debe cumplir los siguientes requisitos: minimo 8 caracteres, '
        'al menos una letra mayuscula, una minuscula, un numero y un caracter especial. '
        'No comparta sus credenciales con terceros.'
    ))
    story.append(Spacer(1, 12))

    story.append(add_heading('Cambiar Contrasena desde el Menu', style_h2, level=1))
    story.append(Paragraph(
        'En cualquier momento puede cambiar su contrasena de forma voluntaria desde dentro del sistema:',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en el menu desplegable con su nombre en la esquina superior derecha de la pantalla.',
        'Seleccione la opcion <b>"Cambiar Contrasena"</b>.',
        'Se abrira una ventana modal donde debe ingresar su <b>contrasena actual</b>, '
        'la <b>nueva contrasena</b> (minimo 8 caracteres, incluyendo mayuscula, minuscula, numero y caracter especial) y <b>confirmar la nueva contrasena</b>.',
        'Haga clic en <b>"Cambiar Contrasena"</b> para guardar los cambios.',
        'Si el cambio es exitoso, vera un mensaje de confirmacion verde y la ventana se cerrara automaticamente.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(tip_box(
        '<b>Consejo:</b> Es recomendable cambiar su contrasena periodicamente por seguridad. '
        'Si olvida su contrasena, debe contactar al Webmaster del sistema para que la restablezca.'
    ))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Cerrar Sesion', style_h2, level=1))
    story.append(Paragraph(
        'Para cerrar sesion, haga clic en el menu desplegable con su nombre en la esquina superior '
        'derecha de la pantalla y seleccione <b>"Cerrar Sesion"</b>. Se recomienda cerrar sesion '
        'siempre que termine de usar el sistema, especialmente en equipos compartidos.',
        style_body
    ))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 3. PANEL DE CONTROL (DASHBOARD)
    # ──────────────────────────────────────────────
    story.extend(add_major_section('3. Panel de Control (Dashboard)'))
    
    story.append(Paragraph(
        'El Dashboard es la pantalla principal del sistema y esta disponible para <b>todos los '
        'perfiles de usuario</b>. Muestra una vision general del estado del proyecto en tiempo real '
        'y se actualiza automaticamente cada 30 segundos.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Tarjetas de Indicadores (KPIs)', style_h2, level=1))
    story.append(Paragraph(
        'En la parte superior del Dashboard encontrara cuatro tarjetas con indicadores clave:',
        style_body
    ))
    story.append(Spacer(1, 6))
    
    kpi_data = [
        [Paragraph('<b>Indicador</b>', style_th), Paragraph('<b>Descripcion</b>', style_th), Paragraph('<b>Detalle</b>', style_th)],
        [Paragraph('PAF Global', style_td), Paragraph('Porcentaje de avance fisico general', style_td_left), 
         Paragraph('Promedio ponderado de todos los frentes activos. Incluye un indicador circular de color.', style_td_left)],
        [Paragraph('Frentes Activos', style_td), Paragraph('Cantidad de frentes de obra activos', style_td_left),
         Paragraph('Numero de alcances con estado "Activo" actualmente.', style_td_left)],
        [Paragraph('Alertas', style_td), Paragraph('Avances pendientes por aprobar', style_td_left),
         Paragraph('Cantidad de reportes de avance que estan en estado "Pendiente" de revision.', style_td_left)],
        [Paragraph('Especialidades', style_td), Paragraph('Numero de especialidades desplegadas', style_td_left),
         Paragraph('Cantidad de especialidades unicas con trabajo en ejecucion.', style_td_left)],
    ]
    story.append(make_table(kpi_data, [CONTENT_W*0.2, CONTENT_W*0.35, CONTENT_W*0.45]))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Mapa de Calor del Hospital', style_h2, level=1))
    story.append(Paragraph(
        'El mapa de calor es una representacion visual del avance por sectores y subsectores del hospital. '
        'Cada celda muestra el nombre del subsector y su porcentaje PAF, codificado por color:',
        style_body
    ))
    story.extend(bullet_list([
        '<b>Gris:</b> Sin avance (0%)',
        '<b>Rojo:</b> Avance critico (menos de 30%)',
        '<b>Amarillo:</b> Avance intermedio (30% - 70%)',
        '<b>Verde:</b> Avance satisfactorio (mas de 70%)',
    ]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        'Al pasar el cursor sobre una celda, se muestra un cuadro informativo con: sector, '
        'especialidad, PAF%, cantidad planificada y cantidad ejecutada.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Grafico de PAF por Sector', style_h2, level=1))
    story.append(Paragraph(
        'Debajo del mapa de calor se muestra un grafico de barras horizontales que representa '
        'el PAF de cada sector, ordenado de mayor a menor avance. Las barras utilizan la misma '
        'codificacion de color (rojo, amarillo, verde) que el mapa de calor.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Sub-pestanas del Dashboard', style_h2, level=1))
    story.append(Paragraph(
        'El Dashboard se organiza en tres sub-pestanas que permiten diferentes vistas del avance:',
        style_body
    ))
    story.append(Spacer(1, 6))
    
    subtab_data = [
        [Paragraph('<b>Sub-pestana</b>', style_th), Paragraph('<b>Descripcion</b>', style_th)],
        [Paragraph('Vista General', style_td), Paragraph('Muestra el resumen global del PAF con todos los indicadores, el mapa de calor y el grafico por sector. Es la vista por defecto.', style_td_left)],
        [Paragraph('Por Ejecutoras', style_td), Paragraph('Desglosa el PAF por Unidad Ejecutora, permitiendo comparar el avance entre los diferentes organismos responsables de la ejecucion de obras.', style_td_left)],
        [Paragraph('Por Macro Especialidades', style_td), Paragraph('Agrupa el PAF por macro especialidades, facilitando la comparacion entre grandes categorias de trabajo (ej: Infraestructura, Electricidad, Plomeria).', style_td_left)],
    ]
    story.append(make_table(subtab_data, [CONTENT_W*0.3, CONTENT_W*0.7]))
    story.append(Spacer(1, 8))

    story.append(add_heading('Actualizacion Automatica', style_h2, level=1))
    story.append(Paragraph(
        'Los datos del Dashboard se refrescan automaticamente cada 30 segundos. Tambien puede '
        'usar el boton de actualizacion manual ubicado en la parte superior para forzar la '
        'recarga de datos en cualquier momento.',
        style_body
    ))
    story.append(Spacer(1, 8))

    story.append(tip_box(
        '<b>URL del sistema:</b> Puede acceder al sistema desde '
        '<b>obras.hospitaljmdelosrios.org.ve</b> en cualquier navegador web moderno.'
    ))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 4. GUIA POR PERFIL DE USUARIO
    # ──────────────────────────────────────────────
    story.extend(add_major_section('4. Guia por Perfil de Usuario'))
    story.append(Paragraph(
        'En esta seccion encontrara instrucciones detalladas segun su perfil de usuario. '
        'Localice su perfil a continuacion y siga las indicaciones correspondientes. '
        'Los avances pasan por un sistema de <b>aprobacion secuencial de 3 niveles</b> con '
        'posibilidad de <b>objecion y subsanacion</b>.',
        style_body
    ))
    story.append(Spacer(1, 12))

    # ── WEBMASTER ──
    story.append(role_banner('WEBMASTER', '#6d28d9'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'El Webmaster es el <b>administrador integral del sistema</b>. Tiene acceso completo a todas '
        'las funcionalidades y es el unico perfil que puede gestionar usuarios, tablas catalogo '
        'y aprobar avances en cualquier nivel sin seguir la secuencia.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_webmaster = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Completo', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Completo', style_td), Paragraph('Crear, editar, eliminar y consultar alcances', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Completo', style_td), Paragraph('Crear, editar, eliminar avances; aprobar cualquier nivel, objetar, declarar subsanada', style_td_left)],
        [Paragraph('Administracion', style_td), Paragraph('Exclusivo', style_td), Paragraph('Gestionar usuarios, tablas catalogo, logos de UE', style_td_left)],
    ]
    story.append(make_table(access_webmaster, [CONTENT_W*0.25, CONTENT_W*0.2, CONTENT_W*0.55]))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Aprobacion en Cualquier Nivel', style_h2, level=1))
    story.append(Paragraph(
        'A diferencia de los demas roles, el Webmaster <b>no esta sujeto a la secuencia de aprobacion</b>. '
        'Puede aprobar el Nivel 1, 2 o 3 en cualquier orden, sin necesidad de que los niveles '
        'previos esten aprobados. Tambien puede <b>revertir cualquier nivel de aprobacion</b> de '
        'vuelta a estado "Pendiente" si se requiere una revision.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Gestion de Usuarios', style_h2, level=1))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Administracion"</b> (solo visible para Webmaster).',
        'Para crear un usuario: haga clic en <b>"Nuevo Usuario"</b>, ingrese nombre, correo, '
        'perfil y contrasena temporal (minimo 8 caracteres, incluyendo mayuscula, minuscula, numero y caracter especial).',
        'Para editar un usuario: haga clic en el icono de <b>lapiz</b> y modifique los campos necesarios.',
        'Para restablecer una contrasena: seleccione la opcion de <b>reset</b> en el usuario correspondiente.',
    ]))
    story.append(Spacer(1, 8))

    story.append(add_heading('Gestion de Tablas Catalogo', style_h2, level=1))
    story.append(Paragraph(
        'Desde la pestana "Administracion", el Webmaster puede gestionar las tablas catalogo del sistema: '
        'especialidades, sectores, subsectores y unidades ejecutoras. Tambien puede subir logos '
        'para las unidades ejecutoras que se muestran en el Dashboard.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Precaucion:</b> Los cambios en las tablas catalogo afectan a todos los usuarios del sistema. '
        'Elimine registros solo si esta seguro de que no estan siendo utilizados en alcances o avances existentes.'
    ))
    story.append(Spacer(1, 12))

    # ── CONTRATISTA ──
    story.append(role_banner('CONTRATISTA', '#2563eb'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'El Contratista es el <b>principal responsable de reportar avances</b> en el sistema. '
        'Su funcion principal es ingresar los reportes de ejecucion, subir la evidencia '
        'fotografica de las obras realizadas y <b>declarar subsanaciones</b> cuando un avance '
        'ha sido objetado.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_contratista = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Completo', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Solo lectura (su UE)', style_td), Paragraph('Consultar y filtrar alcances', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Lectura + Creacion', style_td), Paragraph('Crear reportes, ver detalles, subir fotos, declarar subsanada', style_td_left)],
    ]
    story.append(make_table(access_contratista, [CONTENT_W*0.25, CONTENT_W*0.2, CONTENT_W*0.55]))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Consultar Alcances Planificados', style_h2, level=1))
    story.append(Paragraph(
        'Antes de reportar un avance, puede consultar los alcances planificados para conocer '
        'los frentes de trabajo activos:',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Alcance Planificado"</b> en la barra superior.',
        'Se mostrara una lista de los alcances activos de su Unidad Ejecutora con su especialidad, sector, subsector y estado.',
        'Use los <b>filtros superiores</b> para buscar por sector, especialidad o estado.',
        'Haga clic en cualquier registro para ver sus detalles completos.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Nota:</b> Como Contratista, usted <b>no puede crear ni editar</b> alcances planificados. '
        'Esta funcion es exclusiva del Inspector. Si necesita crear un nuevo alcance, contacte al Inspector asignado.'
    ))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Reportar un Avance de Obra', style_h2, level=1))
    story.append(Paragraph(
        'Esta es su funcion principal en el sistema. Para reportar un avance:',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Avance Ejecutado"</b>.',
        'Haga clic en el boton <b>"Nuevo Avance"</b> (esquina superior derecha).',
        'Seleccione el <b>Alcance Planificado</b> correspondiente al frente de trabajo. Solo se muestran los alcances con estado "Activo".',
        'Ingrese la <b>Cantidad Reportada</b> (valor numerico de lo ejecutado).',
        'Seleccione el <b>Tipo de Trabajo</b>: "Planificado" (si estaba programado) o "Imprevisto" (si fue un trabajo no contemplado).',
        'Seleccione la <b>Fecha de Reporte</b> usando el calendario desplegable.',
        'Suba <b>Fotos de Evidencia</b>: haga clic en el area de carga y seleccione las imagenes desde su dispositivo. Puede subir multiples fotos (maximo 10MB cada una). Las fotos son la prueba visual del trabajo realizado.',
        'Opcionalmente, agregue <b>Notas</b> con observaciones o detalles adicionales.',
        'Haga clic en <b>"Guardar"</b> para enviar el reporte.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(tip_box(
        '<b>Consejo importante:</b> El reporte se creara con estado <b>"Pendiente"</b> y debera pasar '
        'por los 3 niveles de aprobacion: Nivel 1 (Ingeniera Residente), Nivel 2 (Inspector MPPOP) '
        'y Nivel 3 (Directivo Hospital). Asegurese de subir fotos claras y completas como evidencia.'
    ))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Declarar una Objecion como Subsanada', style_h2, level=1))
    story.append(Paragraph(
        'Si un revisor objeta su avance, usted puede declarar la objecion como subsanada:',
        style_body
    ))
    story.extend(step_list([
        'En la lista de avances, identifique los registros con estado <b>"Objetado"</b> (indicador naranja).',
        'Haga clic en el boton <b>"Declarar Subsanada"</b> del avance objetado.',
        'Ingrese las <b>notas de subsanacion</b> describiendo las correcciones realizadas.',
        'Haga clic en <b>"Confirmar"</b>. El estado cambiara a <b>"Subsanado"</b> (indicador azul).',
        'El revisor podra entonces re-evaluar el avance (aprobar, objetar nuevamente o rechazar).',
    ]))
    story.append(Spacer(1, 10))

    story.append(add_heading('Ver Detalles de un Avance', style_h2, level=1))
    story.extend(step_list([
        'En la lista de avances, haga clic en el icono de <b>ojo</b> (Ver detalles) del registro deseado.',
        'Se abrira una vista detallada con toda la informacion del avance: datos del alcance, '
        'cantidad reportada, tipo de trabajo, fecha, estado de aprobacion por nivel, notas y galeria fotografica.',
        'En la galeria puede ver las fotos de evidencia en tamano completo.',
    ]))
    story.append(Spacer(1, 10))

    story.append(add_heading('Filtrar Avances', style_h2, level=1))
    story.append(Paragraph(
        'Use los filtros disponibles en la parte superior de la lista de avances para buscar '
        'por estado de aprobacion (Pendiente, Aprobado, Rechazado, Objetado, Subsanado) y por fecha.',
        style_body
    ))
    story.append(Spacer(1, 12))

    # ── INSPECTOR ──
    story.append(role_banner('INSPECTOR', '#059669'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'El Inspector tiene un rol multiple: <b>gestiona los alcances planificados</b>, '
        '<b>aprueba avances en el Nivel 2</b> en representacion del MPPOP, puede <b>objetar</b> '
        'avances y tambien <b>crear avances</b>. Es responsable de garantizar la calidad y '
        'veracidad de los datos en el sistema.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_inspector = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Completo', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Lectura + Creacion + Edicion', style_td), Paragraph('Crear, editar, consultar y filtrar alcances', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Lectura + Creacion + Aprobacion N2', style_td), Paragraph('Aprobar/objetar/rechazar en N2, crear avances, ver detalles, declarar subsanada', style_td_left)],
    ]
    story.append(make_table(access_inspector, [CONTENT_W*0.25, CONTENT_W*0.25, CONTENT_W*0.50]))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Crear un Alcance Planificado', style_h2, level=1))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Alcance Planificado"</b>.',
        'Haga clic en el boton <b>"Nuevo Alcance"</b> (esquina superior derecha).',
        'Complete el formulario con los siguientes campos:',
    ]))
    story.append(Spacer(1, 6))
    
    alcance_fields = [
        [Paragraph('<b>Campo</b>', style_th), Paragraph('<b>Obligatorio</b>', style_th), Paragraph('<b>Descripcion</b>', style_th)],
        [Paragraph('Especialidad', style_td), Paragraph('Si', style_td), Paragraph('Tipo de especialidad del trabajo (ej: Electricidad, Plomeria)', style_td_left)],
        [Paragraph('Sector / Subsector', style_td), Paragraph('Si', style_td), Paragraph('Ubicacion dentro del hospital. Seleccione primero el sector, luego el subsector.', style_td_left)],
        [Paragraph('Descripcion', style_td), Paragraph('Si', style_td), Paragraph('Descripcion detallada del alcance del trabajo', style_td_left)],
        [Paragraph('Peso Relativo (%)', style_td), Paragraph('No', style_td), Paragraph('Ponderacion del frente en el calculo del PAF global', style_td_left)],
        [Paragraph('Unidad de Medida', style_td), Paragraph('Si', style_td), Paragraph('Unidad para cuantificar el trabajo (ej: m2, ml, unidades)', style_td_left)],
        [Paragraph('Cantidad Planificada', style_td), Paragraph('No', style_td), Paragraph('Cantidad total planificada para el frente', style_td_left)],
        [Paragraph('Unidad Ejecutora', style_td), Paragraph('No', style_td), Paragraph('Organismo responsable de la ejecucion', style_td_left)],
    ]
    story.append(make_table(alcance_fields, [CONTENT_W*0.2, CONTENT_W*0.15, CONTENT_W*0.65]))
    story.append(Spacer(1, 6))
    story.extend(numbered_list([
        'Haga clic en <b>"Guardar"</b> para crear el alcance. Se creara con estado "Activo" por defecto.',
    ]))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Editar un Alcance Planificado', style_h2, level=1))
    story.extend(step_list([
        'En la lista de alcances, haga clic en el icono de <b>lapiz</b> (Editar) del registro deseado.',
        'Modifique los campos necesarios. En modo edicion, tambien puede cambiar el <b>Estado</b> del alcance: Activo, Completado o Suspendido.',
        'Haga clic en <b>"Guardar"</b> para confirmar los cambios.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Precaucion:</b> Cambiar el estado de un alcance a "Completado" o "Suspendido" lo elimina '
        'del calculo del PAF de frentes activos. Solo el Webmaster puede eliminar alcances.'
    ))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Aprobar, Objetar o Rechazar en Nivel 2', style_h2, level=1))
    story.append(Paragraph(
        'Como Inspector, usted aprueba avances en el <b>Nivel 2</b> (representando al MPPOP). '
        'Solo puede aprobar si el Nivel 1 ya fue aprobado por la Ingeniera Residente. '
        'Los avances pendientes de revision se reflejan como "Alertas" en el Dashboard.',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Avance Ejecutado"</b>.',
        'Filtre por avances que tienen <b>Nivel 1 aprobado</b> y <b>Nivel 2 pendiente</b>.',
        'Revise los detalles de cada avance: verifique la cantidad reportada, las fotos de evidencia y las notas.',
        'Para <b>aprobar en Nivel 2</b>: haga clic en el icono de <b>check verde</b>. El Nivel 2 pasara a "Aprobado".',
        'Para <b>objetar</b>: haga clic en el boton <b>"Objetar"</b>. Debe ingresar una razon obligatoria. '
        'El avance pasara a estado "Objetado" (indicador naranja). El creador podra declararlo subsanado.',
        'Para <b>rechazar</b>: haga clic en el icono de <b>X roja</b>. Se le solicitara una razon de rechazo. '
        'El avance pasara a estado "Rechazado" y no se contabilizara.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(tip_box(
        '<b>Recomendacion:</b> Si tiene dudas sobre un avance pero no desea rechazarlo definitivamente, '
        'use la opcion de <b>Objetar</b>. Esto da la oportunidad al creador de corregir y declarar '
        'la subsanacion antes de una decision final.'
    ))
    story.append(Spacer(1, 12))

    # ── INGENIERA RESIDENTE ──
    story.append(role_banner('INGENIERA RESIDENTE', '#7c3aed'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'La Ingeniera Residente tiene un rol activo en el flujo de aprobacion: es responsable de '
        '<b>declarar la obra concluida en el Nivel 1</b>. Tambien puede crear avances, objetar y '
        'declarar subsanaciones.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_ing_residente = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Completo', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Solo lectura (su UE)', style_td), Paragraph('Consultar y filtrar alcances', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Lectura + Creacion + Aprobacion N1', style_td), Paragraph('Declarar concluida (N1), crear avances, objetar, declarar subsanada', style_td_left)],
    ]
    story.append(make_table(access_ing_residente, [CONTENT_W*0.25, CONTENT_W*0.25, CONTENT_W*0.50]))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Aprobar, Objetar o Rechazar en Nivel 1', style_h2, level=1))
    story.append(Paragraph(
        'Como Ingeniera Residente, usted es la primera en la cadena de aprobacion. Su funcion es '
        '<b>declarar la obra como concluida</b> en el Nivel 1, verificando que el trabajo reportado '
        'corresponde a la realidad de la obra.',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Avance Ejecutado"</b>.',
        'Filtre por avances con <b>Nivel 1 pendiente</b>.',
        'Revise los detalles: cantidad reportada, fotos de evidencia y notas.',
        'Para <b>aprobar en Nivel 1</b>: haga clic en el icono de <b>check verde</b> para declarar la obra concluida. '
        'El avance avanzara al Nivel 2 para revision del Inspector.',
        'Para <b>objetar</b>: haga clic en <b>"Objetar"</b> con una razon obligatoria. El avance pasara a "Objetado".',
        'Para <b>rechazar</b>: haga clic en <b>X roja</b> con una razon. El avance pasara a "Rechazado".',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Crear Avances', style_h2, level=1))
    story.append(Paragraph(
        'Ademas de su rol de aprobacion, la Ingeniera Residente puede crear reportes de avance '
        'y declarar objeciones como subsanadas, siguiendo el mismo procedimiento descrito para '
        'el Contratista.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Nota:</b> Su aprobacion en Nivel 1 es requisito para que el Inspector pueda aprobar el Nivel 2. '
        'Si objeta un avance, el creador debera subsanarlo antes de que usted pueda re-evaluar.'
    ))
    story.append(Spacer(1, 12))

    # ── DIRECTIVO HOSPITAL ──
    story.append(role_banner('DIRECTIVO DE HOSPITAL', '#dc2626'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'El Directivo de Hospital tiene un rol clave en el flujo de aprobacion: es responsable de '
        '<b>dar la conformidad final en el Nivel 3</b>. Solo puede aprobar avances que ya tengan '
        'los Niveles 1 y 2 aprobados. Tambien puede objetar avances.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_directivo = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Completo', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('No disponible', style_td), Paragraph('Esta seccion no es visible para este perfil', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Lectura + Aprobacion N3', style_td), Paragraph('Dar conformidad final (N3), objetar, ver detalles y fotos', style_td_left)],
    ]
    story.append(make_table(access_directivo, [CONTENT_W*0.25, CONTENT_W*0.2, CONTENT_W*0.55]))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Dar Conformidad Final (Nivel 3)', style_h2, level=1))
    story.append(Paragraph(
        'Como Directivo, usted da la conformidad final al avance. Solo puede aprobar si los '
        'Niveles 1 y 2 ya estan aprobados:',
        style_body
    ))
    story.extend(step_list([
        'Haga clic en la pestana <b>"Avance Ejecutado"</b>.',
        'Filtre por avances con <b>Nivel 1 y 2 aprobados</b> y <b>Nivel 3 pendiente</b>.',
        'Revise los detalles: cantidad reportada, fotos de evidencia y notas.',
        'Para <b>dar conformidad</b>: haga clic en el icono de <b>check verde</b>. El avance quedara '
        '<b>"Aprobado"</b> en todos los niveles y se integrara al calculo del PAF.',
        'Para <b>objetar</b>: haga clic en <b>"Objetar"</b> con una razon obligatoria. El avance '
        'pasara a estado "Objetado".',
        'Para <b>rechazar</b>: haga clic en <b>X roja</b> con una razon. El avance pasara a "Rechazado".',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Monitoreo del Avance', style_h2, level=1))
    story.append(Paragraph(
        'Desde el Dashboard, usted puede obtener una vision completa del estado del proyecto:',
        style_body
    ))
    story.extend(bullet_list([
        '<b>PAF Global:</b> El indicador principal muestra el porcentaje general de avance de todas las obras.',
        '<b>Mapa de Calor:</b> Identifique rapidamente que areas del hospital tienen avances criticos (rojo), intermedios (amarillo) o satisfactorios (verde).',
        '<b>Grafico por Sector:</b> Compare el avance entre los diferentes sectores del hospital.',
        '<b>Alertas:</b> La tarjeta de alertas indica cuantos avances estan pendientes de su conformidad final.',
    ]))
    story.append(Spacer(1, 6))
    
    story.append(tip_box(
        '<b>Consejo:</b> Si observa que el PAF Global se mantiene en valores bajos o que hay muchas '
        'alertas pendientes, considere solicitar una reunion de seguimiento con el equipo tecnico. '
        'Use la opcion de Objeter si necesita que se corrigan detalles antes de dar conformidad final.'
    ))
    story.append(Spacer(1, 12))

    # ── INGENIERIA HOSPITAL ──
    story.append(role_banner('INGENIERIA DE HOSPITAL', '#0891b2'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'El perfil de Ingenieria de Hospital tiene acceso de <b>solo lectura</b> a todas las secciones '
        'operativas del sistema. Su funcion es realizar seguimiento tecnico tanto de los alcances '
        'planificados como de los avances ejecutados.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_ing_hospital = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Completo', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Solo lectura', style_td), Paragraph('Consultar y filtrar alcances', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Solo lectura', style_td), Paragraph('Ver lista, detalles y fotos de avances', style_td_left)],
    ]
    story.append(make_table(access_ing_hospital, [CONTENT_W*0.25, CONTENT_W*0.2, CONTENT_W*0.55]))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Seguimiento Tecnico', style_h2, level=1))
    story.append(Paragraph(
        'Su perfil le permite realizar un seguimiento integral del proyecto:',
        style_body
    ))
    story.extend(bullet_list([
        '<b>Alcance Planificado:</b> Revise los frentes de trabajo planificados, sus especialidades, '
        'sectores, subsectores, unidades de medida y cantidades planificadas. Use los filtros para '
        'enfocarse en areas especificas.',
        '<b>Avance Ejecutado:</b> Consulte los reportes de avance con sus estados por nivel de aprobacion, '
        'evidencia fotografica y notas. Puede ver si un avance esta Pendiente, Objetado, Subsanado, Aprobado o Rechazado.',
        '<b>Dashboard:</b> Utilice el mapa de calor y los graficos para identificar areas criticas '
        'que requieren atencion prioritaria.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Nota:</b> Su perfil no permite crear, editar, aprobar, objetar ni eliminar registros. '
        'Si identifica situaciones que requieren accion, comuniquese con el Inspector o Webmaster.'
    ))
    story.append(Spacer(1, 12))

    # ── VISITANTE ──
    story.append(role_banner('VISITANTE', '#6b7280'))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph(
        'El Visitante tiene acceso de <b>solo lectura</b> a todas las secciones de consulta del sistema. '
        'No puede crear, editar, aprobar, objetar ni eliminar ningun tipo de registro. Es un perfil '
        'orientado a la transparencia y consulta publica.',
        style_body
    ))
    story.append(Spacer(1, 8))
    
    access_visitante = [
        [Paragraph('<b>Seccion</b>', style_th), Paragraph('<b>Acceso</b>', style_th), Paragraph('<b>Acciones</b>', style_th)],
        [Paragraph('Dashboard', style_td), Paragraph('Solo lectura', style_td), Paragraph('Ver indicadores, mapa de calor, graficos', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Solo lectura', style_td), Paragraph('Consultar y filtrar alcances', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Solo lectura', style_td), Paragraph('Ver lista, detalles y fotos de avances', style_td_left)],
        [Paragraph('Administracion', style_td), Paragraph('No disponible', style_td), Paragraph('Esta seccion no es visible para este perfil', style_td_left)],
    ]
    story.append(make_table(access_visitante, [CONTENT_W*0.25, CONTENT_W*0.2, CONTENT_W*0.55]))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Consultar Informacion', style_h2, level=1))
    story.append(Paragraph(
        'Como Visitante, usted puede navegar libremente por las secciones de consulta del sistema:',
        style_body
    ))
    story.extend(bullet_list([
        '<b>Dashboard:</b> Revise los indicadores clave, el mapa de calor por sectores, los graficos de PAF y las sub-pestanas (Vista General, Por Ejecutoras, Por Macro Especialidades).',
        '<b>Alcance Planificado:</b> Consulte los frentes de trabajo activos, sus especialidades y ubicaciones. Use los filtros para busquedas especificas.',
        '<b>Avance Ejecutado:</b> Vea los reportes de avance, sus estados (Pendiente, Objetado, Subsanado, Aprobado, Rechazado) y la evidencia fotografica asociada.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(warning_box(
        '<b>Nota:</b> Su perfil es exclusivamente de consulta. No puede realizar ninguna accion '
        'modificatoria en el sistema. Si necesita reportar un avance o solicitar una correccion, '
        'contacte al Contratista o Webmaster del sistema.'
    ))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 5. RESUMEN COMPARATIVO DE ACCESOS
    # ──────────────────────────────────────────────
    story.extend(add_major_section('5. Resumen Comparativo de Accesos'))
    
    story.append(Paragraph(
        'La siguiente tabla resume las funcionalidades disponibles para cada perfil de usuario:',
        style_body
    ))
    story.append(Spacer(1, 12))
    
    # Use special styles for this wide table
    style_td_xs = ParagraphStyle('TDXs', fontName=BODY_FONT, fontSize=7.5, leading=10, textColor=TEXT_PRIMARY, alignment=TA_CENTER)
    style_th_xs = ParagraphStyle('THXs', fontName=HEADING_FONT, fontSize=7.5, leading=10, textColor=colors.white, alignment=TA_CENTER)
    style_td_xs_left = ParagraphStyle('TDXsLeft', fontName=BODY_FONT, fontSize=7.5, leading=10, textColor=TEXT_PRIMARY, alignment=TA_LEFT)
    
    summary_data = [
        [Paragraph('<b>Funcionalidad</b>', style_th_xs),
         Paragraph('<b>Webmaster</b>', style_th_xs),
         Paragraph('<b>Contratista</b>', style_th_xs),
         Paragraph('<b>Inspector</b>', style_th_xs),
         Paragraph('<b>Ing. Residente</b>', style_th_xs),
         Paragraph('<b>Directivo</b>', style_th_xs),
         Paragraph('<b>Ing. Hospital</b>', style_th_xs),
         Paragraph('<b>Visitante</b>', style_th_xs)],
        [Paragraph('Ver Dashboard', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), 
         Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs)],
        [Paragraph('Ver Alcance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('Si (su UE)', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si (su UE)', style_td_xs), Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs)],
        [Paragraph('Crear Alcance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Editar Alcance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Eliminar Alcance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Crear Avance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Editar Avance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Aprobar Nivel 1 (Residente)', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Aprobar Nivel 2 (Inspector)', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Aprobar Nivel 3 (Directivo)', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Rechazar (su nivel)', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Objetar (su nivel)', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Declarar Subsanada', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Eliminar Avance', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
        [Paragraph('Ver Detalles/Fotos', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs),
         Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs), Paragraph('Si', style_td_xs)],
        [Paragraph('Administracion', style_td_xs_left), Paragraph('Si', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs),
         Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs), Paragraph('No', style_td_xs)],
    ]
    story.append(make_table(summary_data, [CONTENT_W*0.18, CONTENT_W*0.12, CONTENT_W*0.12, CONTENT_W*0.11, CONTENT_W*0.13, CONTENT_W*0.11, CONTENT_W*0.12, CONTENT_W*0.11]))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 6. FLUJO DE TRABAJO
    # ──────────────────────────────────────────────
    story.extend(add_major_section('6. Flujo de Trabajo del Sistema'))
    
    story.append(Paragraph(
        'El sistema sigue un flujo de trabajo con <b>aprobacion secuencial de 3 niveles</b> y un '
        'mecanismo de <b>objecion/subsanacion</b> que permite la correccion antes del rechazo definitivo. '
        'El Webmaster puede intervenir en cualquier nivel sin seguir la secuencia.',
        style_body
    ))
    story.append(Spacer(1, 10))
    
    story.append(add_heading('Flujo de Aprobacion Secuencial', style_h2, level=1))
    
    flow_data = [
        [Paragraph('<b>Paso</b>', style_th), Paragraph('<b>Responsable</b>', style_th), Paragraph('<b>Accion</b>', style_th), Paragraph('<b>Resultado</b>', style_th)],
        [Paragraph('1', style_td), Paragraph('Inspector', style_td), 
         Paragraph('Crea el Alcance Planificado con los datos del frente de trabajo', style_td_left),
         Paragraph('Alcance registrado con estado "Activo"', style_td_left)],
        [Paragraph('2', style_td), Paragraph('Contratista / Ing. Residente / Inspector',
         style_td), Paragraph('Reporta el Avance Ejecutado con cantidad, fotos y notas', style_td_left),
         Paragraph('Avance registrado con estado "Pendiente" en los 3 niveles', style_td_left)],
        [Paragraph('3', style_td), Paragraph('Ing. Residente (Nivel 1)', style_td),
         Paragraph('Declara la obra concluida: aprueba, objeta o rechaza en Nivel 1', style_td_left),
         Paragraph('Nivel 1: Aprobado, Objetado o Rechazado', style_td_left)],
        [Paragraph('4', style_td), Paragraph('Inspector MPPOP (Nivel 2)', style_td),
         Paragraph('Revisa en representacion del ministerio: aprueba, objeta o rechaza en Nivel 2', style_td_left),
         Paragraph('Nivel 2: Aprobado, Objetado o Rechazado (requiere N1 aprobado)', style_td_left)],
        [Paragraph('5', style_td), Paragraph('Directivo Hospital (Nivel 3)', style_td),
         Paragraph('Da conformidad final: aprueba, objeta o rechaza en Nivel 3', style_td_left),
         Paragraph('Nivel 3: Aprobado, Objetado o Rechazado (requiere N2 aprobado)', style_td_left)],
        [Paragraph('6', style_td), Paragraph('Sistema', style_td),
         Paragraph('Los avances con los 3 niveles aprobados se integran al calculo del PAF', style_td_left),
         Paragraph('PAF Global y por sector actualizado', style_td_left)],
    ]
    story.append(make_table(flow_data, [CONTENT_W*0.08, CONTENT_W*0.22, CONTENT_W*0.38, CONTENT_W*0.32]))
    story.append(Spacer(1, 12))
    
    story.append(add_heading('Regla de Aprobacion Secuencial', style_h2, level=1))
    story.append(Paragraph(
        'La aprobacion es estrictamente secuencial:',
        style_body
    ))
    story.extend(bullet_list([
        '<b>Nivel 2</b> solo puede aprobarse si el <b>Nivel 1 esta aprobado</b>.',
        '<b>Nivel 3</b> solo puede aprobarse si el <b>Nivel 2 esta aprobado</b>.',
        'Un avance se considera <b>"Aprobado"</b> solo cuando los 3 niveles estan aprobados.',
        'Si <b>cualquier nivel rechaza</b>, el status general es <b>"Rechazado"</b>.',
        'El <b>Webmaster puede aprobar cualquier nivel</b> sin seguir la secuencia y puede revertir '
        'cualquier nivel de vuelta a "Pendiente".',
    ]))
    story.append(Spacer(1, 10))

    story.append(add_heading('Flujo de Objecion y Subsanacion', style_h2, level=1))
    story.append(Paragraph(
        'El mecanismo de objecion/subsanacion es un estado intermedio entre aprobar y rechazar '
        'que permite la correccion del avance:',
        style_body
    ))
    story.append(Spacer(1, 6))
    
    objection_data = [
        [Paragraph('<b>Paso</b>', style_th), Paragraph('<b>Accion</b>', style_th), Paragraph('<b>Descripcion</b>', style_th), Paragraph('<b>Indicador</b>', style_th)],
        [Paragraph('1', style_td), Paragraph('Objetar', style_td),
         Paragraph('El revisor objeta el avance con una razon obligatoria. No es un rechazo definitivo sino una solicitud de correccion.', style_td_left),
         Paragraph('Naranja (Objetado)', style_td)],
        [Paragraph('2', style_td), Paragraph('Declarar Subsanada', style_td),
         Paragraph('El creador del avance declara que la objecion fue atendida, con notas explicativas de las correcciones.', style_td_left),
         Paragraph('Azul (Subsanado)', style_td)],
        [Paragraph('3', style_td), Paragraph('Re-evaluacion', style_td),
         Paragraph('El revisor re-evalua el avance: puede aprobar, objetar nuevamente o rechazar.', style_td_left),
         Paragraph('Segun decision', style_td)],
    ]
    story.append(make_table(objection_data, [CONTENT_W*0.08, CONTENT_W*0.18, CONTENT_W*0.54, CONTENT_W*0.20]))
    story.append(Spacer(1, 8))
    
    story.append(add_heading('Prioridad de Estados de Aprobacion', style_h2, level=1))
    story.append(Paragraph(
        'El estado general de aprobacion (status_aprobacion) se calcula automaticamente con la '
        'siguiente prioridad:',
        style_body
    ))
    story.extend(numbered_list([
        '<b>Rechazado</b> (prioridad maxima) - Si cualquier nivel rechaza.',
        '<b>Objetado</b> - Si cualquier nivel objeta y no ha sido subsanado.',
        '<b>Subsanado</b> - Si una objecion fue declarada subsanada y espera re-evaluacion.',
        '<b>Aprobado</b> - Si los 3 niveles estan aprobados.',
        '<b>Pendiente</b> (prioridad minima) - Si algun nivel aun no ha sido revisado.',
    ]))
    story.append(Spacer(1, 8))
    
    story.append(tip_box(
        '<b>Clave del exito:</b> La comunicacion oportuna entre todos los actores es fundamental. '
        'Los creadores deben reportar avances con evidencia completa, los revisores deben '
        'evaluar en el menor tiempo posible, y el mecanismo de objecion/subsanacion debe usarse '
        'agilmente para mantener el PAF actualizado.'
    ))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 7. PREGUNTAS FRECUENTES
    # ──────────────────────────────────────────────
    story.extend(add_major_section('7. Preguntas Frecuentes'))
    
    faqs = [
        ('Olvide mi contrasena. Que puedo hacer?',
         'Desde el menu de usuario, seleccione <b>"Cambiar Contrasena"</b> si aun recuerda su contrasena '
         'actual. Si la olvido completamente, comuniquese con el Webmaster del sistema para que '
         'restablezca su acceso. No hay funcion de recuperacion automatica de contrasena.'),
        
        ('Por que no veo la pestana "Alcance Planificado"?',
         'Si tiene el perfil de Directivo de Hospital o Visitante, esta pestana no esta disponible '
         'para su rol. Los demas perfiles pueden verla en la barra de navegacion superior.'),
        
        ('Puedo crear un avance si no hay alcances activos?',
         'No. Para reportar un avance, debe existir al menos un Alcance Planificado con estado "Activo". '
         'Solo puede seleccionar de la lista de alcances activos disponibles para su Unidad Ejecutora.'),
        
        ('Que pasa si mi avance es objetado?',
         'Si un revisor objeta su avance, recibira la razon de la objecion en las notas del registro. '
         'Puede revisar las observaciones y hacer clic en <b>"Declarar Subsanada"</b> con notas explicativas '
         'de las correcciones realizadas. El revisor entonces re-evaluara el avance y podra aprobar, '
         'objetar nuevamente o rechazar.'),
        
        ('Que significa que un avance este "Objetado" o "Subsanado"?',
         '<b>Objetado</b> (indicador naranja) significa que un revisor solicita correcciones antes de '
         'aprobar. No es un rechazo definitivo. <b>Subsanado</b> (indicador azul) significa que el '
         'creador declaro que las correcciones fueron realizadas y espera re-evaluacion del revisor.'),
        
        ('Como se calcula el PAF Global?',
         'El PAF Global es un promedio ponderado donde cada frente de trabajo contribuye segun su '
         'Peso Relativo. Solo se consideran los alcances con estado "Activo" y los avances con '
         'los 3 niveles de aprobacion "Aprobados".'),
        
        ('Puedo usar el sistema desde mi telefono movil?',
         'Si, el sistema es responsive y se adapta a dispositivos moviles. Sin embargo, para una '
         'mejor experiencia al subir fotos y completar formularios, se recomienda usar una '
         'computadora o tablet.'),
        
        ('Con que frecuencia se actualizan los datos del Dashboard?',
         'Los datos se actualizan automaticamente cada 30 segundos. Tambien puede forzar la '
         'actualizacion usando el boton de recarga manual.'),
        
        ('Puedo cambiar mi perfil de usuario?',
         'No. Los perfiles son asignados por el Webmaster del sistema y no pueden ser '
         'modificados por el usuario. Si cree que su perfil es incorrecto, contacte al Webmaster.'),
        
        ('Que puede hacer el perfil Visitante?',
         'El Visitante tiene acceso de solo lectura a Dashboard, Alcance Planificado y Avance Ejecutado. '
         'No puede crear, editar, aprobar, objetar ni eliminar ningun registro. Tampoco puede acceder '
         'a la pestana de Administracion. Es un perfil orientado a la transparencia y consulta publica.'),
        
        ('Cuales son los requisitos de contrasena?',
         'La contrasena debe tener un minimo de 8 caracteres e incluir al menos: una letra mayuscula, '
         'una letra minuscula, un numero y un caracter especial. Esto aplica para el primer cambio de '
         'contrasena, cambio voluntario, creacion de nuevos usuarios y restablecimiento de contrasena.'),
    ]
    
    for i, (q, a) in enumerate(faqs, 1):
        story.append(Paragraph('<b>%d. %s</b>' % (i, q), style_h3))
        story.append(Paragraph(a, style_body))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 8. GLOSARIO
    # ──────────────────────────────────────────────
    story.extend(add_major_section('8. Glosario de Terminos'))
    
    glossary_data = [
        [Paragraph('<b>Termino</b>', style_th), Paragraph('<b>Definicion</b>', style_th)],
        [Paragraph('PAF', style_td), Paragraph('Porcentaje de Avance Fisico. Indicador que mide el progreso real respecto al planificado.', style_td_left)],
        [Paragraph('Alcance Planificado', style_td), Paragraph('Registro que define un frente de trabajo: que se hara, donde, cuanto se planea ejecutar y su peso relativo.', style_td_left)],
        [Paragraph('Avance Ejecutado', style_td), Paragraph('Reporte de la cantidad de trabajo realizada en un frente, con evidencia fotografica.', style_td_left)],
        [Paragraph('Peso Relativo', style_td), Paragraph('Porcentaje de ponderacion de un frente de trabajo en el calculo del PAF global.', style_td_left)],
        [Paragraph('Frente de Obra', style_td), Paragraph('Cada uno de los ambitos de trabajo definidos en los alcances planificados.', style_td_left)],
        [Paragraph('Especialidad', style_td), Paragraph('Tipo de trabajo tecnico (ej: Electricidad, Plomeria, Estructura).', style_td_left)],
        [Paragraph('Sector', style_td), Paragraph('Area del hospital donde se ejecuta el trabajo (ej: Emergencia, Hospitalizacion).', style_td_left)],
        [Paragraph('Subsector', style_td), Paragraph('Subdivision del sector que identifica la ubicacion especifica dentro del area.', style_td_left)],
        [Paragraph('Estado de Aprobacion', style_td), Paragraph('Estado de revision del avance reportado: Pendiente, Objetado, Subsanado, Aprobado o Rechazado.', style_td_left)],
        [Paragraph('Objecion', style_td), Paragraph('Estado intermedio donde el revisor solicita correcciones al avance sin rechazarlo definitivamente. Indicador naranja.', style_td_left)],
        [Paragraph('Subsanacion', style_td), Paragraph('Declaracion del creador indicando que las objeciones fueron atendidas. Indicador azul. Requiere re-evaluacion del revisor.', style_td_left)],
        [Paragraph('Aprobacion Secuencial', style_td), Paragraph('Sistema de 3 niveles donde cada nivel requiere la aprobacion del nivel anterior: N1 (Residente), N2 (Inspector), N3 (Directivo).', style_td_left)],
        [Paragraph('Webmaster', style_td), Paragraph('Rol de administrador integral del sistema. Puede aprobar cualquier nivel sin seguir la secuencia, gestionar usuarios y tablas catalogo.', style_td_left)],
        [Paragraph('Visitante', style_td), Paragraph('Rol de solo lectura con acceso a Dashboard, Alcance y Avance. No puede realizar ninguna accion modificatoria.', style_td_left)],
    ]
    story.append(make_table(glossary_data, [CONTENT_W*0.28, CONTENT_W*0.72]))
    story.append(Spacer(1, 18))

    # ──────────────────────────────────────────────
    # 9. CONTACTO Y SOPORTE
    # ──────────────────────────────────────────────
    story.extend(add_major_section('9. Contacto y Soporte'))
    
    story.append(Paragraph(
        'Si tiene problemas tecos o consultas sobre el uso del sistema, puede comunicarse con:',
        style_body
    ))
    story.append(Spacer(1, 8))
    story.extend(bullet_list([
        '<b>Webmaster del Sistema:</b> Para problemas de acceso, cambio de credenciales, errores en la plataforma o gestion de usuarios.',
        '<b>Inspector Asignado:</b> Para consultas sobre alcances, aprobacion de avances o flujo de trabajo.',
        '<b>Equipo de Gestion del Proyecto:</b> Para consultas sobre el contenido de los datos o modificaciones en los frentes de trabajo.',
    ]))
    story.append(Spacer(1, 12))
    
    story.append(Paragraph(
        'Este manual fue preparado para el personal operativo del proyecto de recuperacion '
        'del Hospital de Ninos J.M. de los Rios. Para sugerencias de mejora del documento, '
        'contacte al equipo de gestion.',
        style_body
    ))
    story.append(Spacer(1, 12))

    # ──────────────────────────────────────────────
    # 7. INSTITUCIONES PARTICIPANTES
    # ──────────────────────────────────────────────
    story.extend(add_major_section('7. Instituciones Participantes'))

    story.append(Paragraph(
        'Las siguientes instituciones participan como Unidades Ejecutoras en las obras de '
        'recuperacion del Hospital de Ninos J.M. de los Rios:',
        style_body
    ))
    story.append(Spacer(1, 12))

    inst_data = [
        [Paragraph('<b>Institucion</b>', style_th), Paragraph('<b>Siglas</b>', style_th), Paragraph('<b>Area</b>', style_th)],
        [Paragraph('Vicepresidencia de Obras y Servicios Publicos', style_td_left), Paragraph('VSOPS', style_td), Paragraph('Coordinacion general del proyecto', style_td_left)],
        [Paragraph('Hospital de Ninos J.M. de los Rios', style_td_left), Paragraph('HJM', style_td), Paragraph('Institucion beneficiaria', style_td_left)],
        [Paragraph('Alcaldia del Municipio Libertador de Caracas', style_td_left), Paragraph('Alcaldia CCS', style_td), Paragraph('Infraestructura civil y apoyo municipal', style_td_left)],
        [Paragraph('CORPOELEC Industrial', style_td_left), Paragraph('CORPOELEC Ind.', style_td), Paragraph('Sistema electrico y generacion', style_td_left)],
        [Paragraph('Fundacion para el Desarrollo Endogeno Energético y Habitacional', style_td_left), Paragraph('FUNDEEH', style_td), Paragraph('Desarrollo endógeno energético y habitacional', style_td_left)],
        [Paragraph('Hidrologia de Venezuela', style_td_left), Paragraph('Hidroven', style_td), Paragraph('Sistema hidrico y sanitario', style_td_left)],
        [Paragraph('Compania Anonima Nacional Telefonos de Venezuela', style_td_left), Paragraph('CANTv', style_td), Paragraph('Telecomunicaciones', style_td_left)],
        [Paragraph('Ministerio del Poder Popular para el Agua', style_td_left), Paragraph('Minaguas', style_td), Paragraph('Suministro y gestion del agua', style_td_left)],
        [Paragraph('Ministerio del Poder Popular para Obras Publicas', style_td_left), Paragraph('MPPOP', style_td), Paragraph('Obras publicas e infraestructura', style_td_left)],
    ]
    story.append(make_table(inst_data, [CONTENT_W*0.45, CONTENT_W*0.15, CONTENT_W*0.40]))
    story.append(Spacer(1, 16))

    # ──────────────────────────────────────────────
    # CREDITOS
    # ──────────────────────────────────────────────
    story.append(HRFlowable(width='60%', thickness=1, color=TEXT_MUTED, spaceAfter=16, spaceBefore=24))

    style_credits_title = ParagraphStyle(
        'CreditsTitle', fontName=HEADING_FONT, fontSize=14, leading=20,
        textColor=ACCENT, alignment=TA_CENTER, spaceBefore=8, spaceAfter=6
    )
    style_credits_body = ParagraphStyle(
        'CreditsBody', fontName=BODY_FONT, fontSize=11, leading=16,
        textColor=TEXT_PRIMARY, alignment=TA_CENTER, spaceAfter=4
    )
    style_credits_small = ParagraphStyle(
        'CreditsSmall', fontName=BODY_FONT, fontSize=9, leading=14,
        textColor=TEXT_MUTED, alignment=TA_CENTER, spaceAfter=4
    )

    story.append(Paragraph('Desarrollo y Soporte Tecnologico', style_credits_title))
    story.append(Spacer(1, 8))
    story.append(Paragraph('<b>Z.ai</b>', ParagraphStyle(
        'CreditsBrand', fontName=HEADING_FONT, fontSize=20, leading=28,
        textColor=ACCENT, alignment=TA_CENTER, spaceAfter=6
    )))
    story.append(Paragraph('IT Development by <b>@libnimaster</b>', style_credits_body))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        'Plataforma de seguimiento de obras desarrollada para el '
        'Hospital de Ninos J.M. de los Rios — Junio 2026',
        style_credits_small
    ))

    return story


# ━━ COVER PAGE (HTML/Playwright) ━━
def create_cover_html():
    """Create the cover page HTML using Template 07 (Solid Sidebar - Institutional)."""
    return '''<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Manual de Usuario - Sistema PAF</title>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap" rel="stylesheet">
<style>
  @page {
    size: 794px 1123px;
    margin: 0;
  }
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  html, body {
    width: 794px;
    height: 1123px;
    margin: 0;
    padding: 0;
    overflow: hidden;
    font-family: 'Poppins', sans-serif;
  }
  .cover {
    width: 794px;
    height: 1123px;
    position: relative;
    background: #ffffff;
  }
  
  /* Layer 1 - Background */
  .layer-bg {
    position: absolute;
    inset: 0;
    overflow: hidden;
    z-index: 1;
  }
  .sidebar {
    position: absolute;
    left: 0;
    top: 0;
    width: 79px;
    height: 1123px;
    background: #5d39cc;
  }
  .sidebar-watermark {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%) rotate(-90deg);
    font-size: 80px;
    font-weight: 800;
    color: rgba(255,255,255,0.15);
    white-space: nowrap;
    letter-spacing: 6px;
  }
  .bottom-accent {
    position: absolute;
    left: 0;
    bottom: 0;
    width: 794px;
    height: 8px;
    background: #5d39cc;
  }

  /* Layer 2 - Structure */
  .layer-structure {
    position: absolute;
    inset: 0;
    z-index: 2;
  }
  .hline {
    position: absolute;
    left: 119px;
    bottom: 140px;
    width: 600px;
    height: 1px;
    background: rgba(93,57,204,0.3);
  }

  /* Layer 3 - Content */
  .layer-content {
    position: absolute;
    inset: 0;
    z-index: 3;
    padding-left: 119px;
    padding-right: 60px;
  }
  .kicker {
    position: absolute;
    left: 119px;
    top: 120px;
    font-size: 14px;
    font-weight: 400;
    letter-spacing: 4px;
    text-transform: uppercase;
    color: rgba(27,26,24,0.6);
  }
  .hero-title {
    position: absolute;
    left: 119px;
    top: 180px;
    width: 600px;
    font-size: 42px;
    font-weight: 800;
    color: #5d39cc;
    line-height: 1.15;
  }
  .summary {
    position: absolute;
    left: 119px;
    top: 390px;
    width: 500px;
    font-size: 16px;
    font-weight: 400;
    color: rgba(27,26,24,0.85);
    line-height: 1.6;
  }
  .meta-block {
    position: absolute;
    left: 119px;
    top: 560px;
  }
  .meta-line {
    font-size: 15px;
    font-weight: 400;
    color: #1b1a18;
    line-height: 2.0;
  }
  .meta-label {
    font-weight: 600;
    color: #5d39cc;
  }
  .footer-left {
    position: absolute;
    left: 119px;
    bottom: 70px;
    font-size: 13px;
    font-weight: 400;
    color: rgba(27,26,24,0.6);
  }
  .footer-right {
    position: absolute;
    right: 60px;
    bottom: 70px;
    font-size: 13px;
    font-weight: 400;
    color: rgba(27,26,24,0.6);
  }
  .version-badge {
    display: inline-block;
    background: #5d39cc;
    color: white;
    padding: 3px 12px;
    border-radius: 4px;
    font-size: 12px;
    font-weight: 600;
    margin-left: 8px;
  }
</style>
</head>
<body>
<div class="cover">
  <!-- Layer 1 - Background -->
  <div class="layer-bg">
    <div class="sidebar">
      <div class="sidebar-watermark">MANUAL</div>
    </div>
    <div class="bottom-accent"></div>
  </div>
  
  <!-- Layer 2 - Structure -->
  <div class="layer-structure">
    <div class="hline"></div>
  </div>
  
  <!-- Layer 3 - Content -->
  <div class="layer-content">
    <div class="kicker">Guia de Usuario</div>
    <div class="hero-title">Sistema de Seguimiento<br>PAF</div>
    <div class="summary">
      Manual de instrucciones para el uso del sistema de seguimiento de 
      Porcentaje de Avance Fisico (PAF) del Hospital de Ninos 
      J.M. de los Rios. Incluye 7 perfiles de usuario, sistema de 
      aprobacion secuencial de 3 niveles y flujo de objecion/subsanacion.
    </div>
    <div class="meta-block">
      <div class="meta-line"><span class="meta-label">Institucion:</span> Hospital de Ninos J.M. de los Rios</div>
      <div class="meta-line"><span class="meta-label">Proyecto:</span> Recuperacion Institucional</div>
      <div class="meta-line"><span class="meta-label">Fecha:</span> Junio 2026</div>
      <div class="meta-line"><span class="meta-label">Clasificacion:</span> Uso Interno <span class="version-badge">v3.2</span></div>
    </div>
    <div class="footer-left">Hospital de Ninos J.M. de los Rios</div>
    <div class="footer-right">VSOPS - Obras JM</div>
  </div>
</div>
</body>
</html>'''


def render_cover(html_content, output_path):
    """Render the HTML cover to PDF using html2poster.js."""
    scripts_dir = os.path.join(os.path.expanduser('~'), 'my-project', 'skills', 'pdf', 'scripts')
    html_path = '/tmp/cover_manual.html'
    
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    subprocess.run([
        'node', os.path.join(scripts_dir, 'html2poster.js'),
        html_path, '--output', output_path,
        '--width', '794px',
    ], check=True)
    
    return output_path


def merge_cover_body(cover_pdf, body_pdf, output_pdf):
    """Merge cover + body into a single PDF."""
    from pypdf import PdfReader, PdfWriter, Transformation
    
    A4_W, A4_H = 595.28, 841.89
    
    def normalize_page(page):
        box = page.mediabox
        w, h = float(box.width), float(box.height)
        if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
            sx, sy = A4_W / w, A4_H / h
            page.add_transformation(Transformation().scale(sx=sx, sy=sy))
            page.mediabox.lower_left = (0, 0)
            page.mediabox.upper_right = (A4_W, A4_H)
        return page
    
    writer = PdfWriter()
    cover_page = PdfReader(cover_pdf).pages[0]
    writer.add_page(normalize_page(cover_page))
    
    for page in PdfReader(body_pdf).pages:
        writer.add_page(normalize_page(page))
    
    writer.add_metadata({
        '/Title': 'Manual de Usuario - Sistema PAF Hospital de Ninos J.M. de los Rios',
        '/Author': 'VSOPS - Obras JM',
        '/Creator': 'Z.ai',
        '/Subject': 'Manual de instrucciones del Sistema de Seguimiento de Porcentaje de Avance Fisico',
    })
    
    with open(output_pdf, 'wb') as f:
        writer.write(f)


# ━━ MAIN ━━
if __name__ == '__main__':
    output_dir = '/home/z/my-project'
    body_pdf = os.path.join(output_dir, 'manual_body.pdf')
    cover_pdf = os.path.join(output_dir, 'manual_cover.pdf')
    final_pdf = os.path.join(output_dir, 'Manual_Usuario_Sistema_PAF.pdf')
    
    print("Generando cuerpo del documento...")
    doc = TocDocTemplate(
        body_pdf,
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title='Manual de Usuario - Sistema PAF',
        author='VSOPS - Obras JM',
    )
    
    story = build_content()
    doc.multiBuild(story)
    print("Cuerpo generado:", body_pdf)
    
    print("Generando portada...")
    cover_html = create_cover_html()
    render_cover(cover_html, cover_pdf)
    print("Portada generada:", cover_pdf)
    
    print("Fusionando portada y cuerpo...")
    merge_cover_body(cover_pdf, body_pdf, final_pdf)
    print("PDF final generado:", final_pdf)
    
    # Cleanup temp files
    for f in [body_pdf, cover_pdf]:
        if os.path.exists(f):
            os.remove(f)
    
    print("Proceso completado exitosamente!")
